In [1]:
print("hello i'm sankhyapriyo dey")
print("i'm a student of MSIT doing python")

hello i'm sankhyapriyo dey
i'm a student of MSIT doing python

In [ ]:
age = 18
age = int(age)

if age >= 18 :
    print('you are an adult')
    print("you can vote")

elif age <= 3 :
    print("you are a child")
    print("you can not vote")

else :
    print("input in valid")

you are an adult
you can vote

In [ ]:
a = input("write the 1st number : ")
b = input("write the 2nd number : ")

a = int(a)
b = int(b)

if a>b :
  print("the 1st number is greater than the 2st number")

elif a<b :
  print("the 2nd number is greater than the 1st number")

else :
  print("invalid input !!")

write the 1st number : 10
write the 2nd number : 4
the 1st number is greater than the 1st number

In [ ]:
a = input("enter the 1st number: ")
b = input("enter the 2ms number: ")

a = int(a)
b = int(b)

print("the sum of those numbers are : ")
print(a + b)

enter the 1st number: 12
enter the 2ms number: 14
the sum of those numbers are :
26

In [ ]:
a = input("enter the number u want to loop:")
a = int(a)
x = range(a)
for n in x:
  print(n)

enter the number u want to loop:4
0
1
2
3

hello my name is sankhyapriyo dey

i'm the the one wo is coding this bullshit !!

In [ ]:
x = range(10)
print(x)

range(0, 10)

In [ ]:
i = 5
while i >= 1 :
  print(i * "*")
  i = i - 1

*****
****
***
**
*

In [ ]:
#the position starts from 0 thin 1 , 2 , 3 .......
marks = [12,23,34,45]
print(marks)
print(marks[0])
print(marks[2])
print(marks[0:2])

[12, 23, 34, 45]
12
34
[12, 23]

In [ ]:
marks = [12,23,34,45]     #this is a list of marks
print(marks)
print(56 in marks)
marks.append(56)          #adding a number in the list
print(marks)
marks.insert(1,20)        #adding a number in the list with it's position
print(marks)
print(99 in marks)
print(12 in marks)
print(len(marks))         #asking how many numbers are there
marks.clear()             #deletes all the maks in the list
print(marks)

[12, 23, 34, 45]
False
[12, 23, 34, 45, 56]
[12, 20, 23, 34, 45, 56]
False
True
6
[]

In [ ]:
students = ["sankhya","sankhya1","sankhya2","sankhya3","sankhya4"]
for student in students :
  if student == "sankhya2" :
    break
  print(student)

sankhya
sankhya1

In [ ]:
students = ["sankhya1","sankhya2","sankhya3","sankhya4","sankhya5"]
for student in students :
  if student == "sankhya3":
    continue
  print(student)

sankhya1
sankhya2
sankhya4
sankhya5

In [ ]:
marks = (90,91,92,93,94,94,94)
print(marks.count(90))
print(marks.count(94))
print(marks.index(91))
print(marks)

1
3
1
(90, 91, 92, 93, 94, 94, 94)

In [ ]:
marks = {"english" : 99 , "maths" : 93}
information = {"sankhya1" : "sankhya2"}
print(marks)
print(marks["english"])
print(marks["maths"])
marks["physics"] = 98
print(marks)
marks["physics"] = 92
marks["maths"] = 100
print(marks)

{'english': 99, 'maths': 93}
99
93
{'english': 99, 'maths': 93, 'physics': 98}
{'english': 99, 'maths': 100, 'physics': 92}

In [ ]:
print(round(3.75))
print(round(3.75,1))
print(round(3.759,2))
#ok well now i get it

4
3.8
3.76

In [ ]:
courses = [ "maths","chemistry","physics","computer"]
courses_2 = ["arts","language"]

courses.append("welcome !!")
print(courses)
courses.insert(0,"subjects are")
print(courses)
courses.append(courses_2)   #makes it show like a list in a list
print(courses)
courses.extend(courses_2)
print(courses)              #adds it like an element in the list
courses.remove("maths")
print(courses)

['maths', 'chemistry', 'physics', 'computer', 'welcome !!']
['subjects are', 'maths', 'chemistry', 'physics', 'computer', 'welcome !!']
['subjects are', 'maths', 'chemistry', 'physics', 'computer', 'welcome !!', ['arts', 'language']]
['subjects are', 'maths', 'chemistry', 'physics', 'computer', 'welcome !!', ['arts', 'language'], 'arts', 'language']
['subjects are', 'chemistry', 'physics', 'computer', 'welcome !!', ['arts', 'language'], 'arts', 'language']

In [ ]:
def func1(a,b):
    c = a+b
    return(c)
d= func1(4,6)   #use of a function
print(d)

enter a number :5
not prime !!

In [ ]:
def func1(a,b):
    c = (a*b)/2
    return(c)
d= func1(4,6)   #use of a triangle
print("the are of the triangle is :")
print(d)

the are of the triangle is :
12.0

In [ ]:
def func1(a,b):
    c = (a*b)
    return(c)
d= func1(4,6)   #use of a square
print("the are of the square is :")
print(d)

the are of the square is :
24

In [ ]:
def func1(a):
    c = 3.14*a*a
    return(c)
d= func1(4)   #use of a circle
print("the are of the circle is :")
print(d)

the are of the circle is :
50.24

In [ ]:
import math

def func1(a,b,c):
    s = (a+b+c)/2
    area = math.sqrt(s*(s-a)*(s-b)*(s-c))
    return(area)
d= func1(4,6,8)   #use of a triangle
print("the are of the triangle is :")
print(d)

the are of the triangle is :
11.61895003862225

In [ ]:
import math

def surface_area(radius,height):
    calculation = math.sqrt( height**2 + radius**2 )
    area = math.pi * radius * ( radius + calculation )
    return area

area = surface_area(7,10)
print("the are of the cone is :")
print(area)

the are of the cone is :
422.3742181620695

In [ ]:
import math

def cone_surface_area(radius, height):
    slant_height = math.sqrt(radius**2 + height**2)
    surface_area = math.pi * radius * (radius + slant_height)

    return surface_area

cone_radius = float(input("Enter the radius of the cone: "))
cone_height = float(input("Enter the height of the cone: "))

area = cone_surface_area(cone_radius, cone_height)
print(f"The surface area of the cone is: {area:.2f}")

Enter the radius of the cone: 7
Enter the height of the cone: 12
The surface area of the cone is: 459.45

In [ ]:
import math

def cone_surface_area(radius,height):
  slant_height = math.sqrt(radius**2 + height**2)
  surface_area = math.pi * radius * (radius + slant_height)

  return surface_area

cone_radius = input("enter the radius of the cone : ")
cone_height = input("enter the height of the cone : ")

cone_radius = float(cone_radius)
cone_height = float(cone_height)

area = cone_surface_area(cone_radius,cone_height)
print(f"the surface area of the cone is : {area:.2f}")

enter the radius of the cone : 7
enter the height of the cone : 12
the surface area of the cone is : 459.45

In [ ]:
subjects = ["maths" , "physics" , "chemistry" , "histry"]

popped = subjects.pop()
subjects.pop()   #will remove the last value in the list e

print(popped)
print(subjects)

histry
['maths', 'physics']

In [ ]:
subjects = ["maths" , "physics" , "comsi" , "biology" , "histry"]
numbers = [ 1,2,4,5,6]

subjects.sort()
subjects.reverse()

numbers.sort()
numbers.reverse()

print(subjects)
print(numbers)

In [ ]:
subjects = ["maths" , "physics" , "comsi" , "biology" , "histry"]
numbers = [ 1,2,4,5,6]

subjects.sort(reverse = True)
#numbers.reverse(sort = True)  #will not work because reverse does nopt takes any arguments
numbers.sort(reverse = True)

print(subjects)
print(numbers)

['physics', 'maths', 'histry', 'comsi', 'biology']
[6, 5, 4, 2, 1]

In [ ]:
subjects = ["maths" , "physics" , "comsi" , "biology" , "histry"]
numbers = [ 1,2,4,5,6]

reversed_subjects = reversed(subjects)
sorted_subjects = sorted(subjects)

reversed_numbers = reversed(numbers)
sorted_numbers = sorted(numbers)

print(reversed_numbers)
print(reversed_subjects)

print(sorted_subjects)
print(sorted_numbers)

print(subjects)
print(numbers)

<list_reverseiterator object at 0x799de2f29c90>
<list_reverseiterator object at 0x799de2f2a860>
['biology', 'comsi', 'histry', 'maths', 'physics']
[1, 2, 4, 5, 6]
['maths', 'physics', 'comsi', 'biology', 'histry']
[1, 2, 4, 5, 6]

In [ ]:
subjects = ["maths" , "physics" , "comsi" , "biology" , "history"]
numbers = [ 1,2,4,5,6]

print(subjects)

print(min(numbers))
print(max(numbers))
print(min(subjects))  #the samne for max and min
print(sum(numbers))

print(subjects.index("history"))
print("maths" in subjects)
print("arts" in subjects)

for course in subjects:
  print(course)

for index, course in enumerate(subjects, start = 1) :
  print(index, course)

subjects_str = ' , ' .join(subjects)
print(subjects_str)

subjects_list = subjects_str.split(' , ')
print(subjects_list)

['maths', 'physics', 'comsi', 'biology', 'history']
1
6
biology
18
4
True
False
maths
physics
comsi
biology
history
1 maths
2 physics
3 comsi
4 biology
5 history
maths , physics , comsi , biology , history
['maths', 'physics', 'comsi', 'biology', 'history']

In [ ]:
list_1 = ["maths" , "physics" , "biology" , "chemistry" , "compsi"]
list_2 = list_1

print(list_1)
print(list_2)

list_1[0] = "art" #this same ything cudnt be done by a touple

print(list_1)
print(list_2)

['maths', 'physics', 'biology', 'chemistry', 'compsi']
['maths', 'physics', 'biology', 'chemistry', 'compsi']
['art', 'physics', 'biology', 'chemistry', 'compsi']
['art', 'physics', 'biology', 'chemistry', 'compsi']

In [ ]:
touple_1 = ("maths" , "physics" , "biology" , "chemistry" , "compsi")
touple_2 = touple_1

print(touple_1)
print(touple_2)

touple_1[0] = "art" #error

print(touple_1)
print(touple_2)

('maths', 'physics', 'biology', 'chemistry', 'compsi')
('maths', 'physics', 'biology', 'chemistry', 'compsi')

TypeError: ignored

In [ ]:
science_courses = {"maths" , "physics" , "chemistry" , "biology" , "maths"}
art_courses = {"maths" , "physics" , "geography" , "history"}

print(science_courses) #it will randomize the output , because position holding doesnt affect any sets

print(science_courses.intersection(art_courses))
print(science_courses.union(art_courses))                #normal set formulas also works in this programme
print(science_courses.difference(art_courses))

{'physics', 'chemistry', 'biology', 'maths'}
{'physics', 'maths'}
{'history', 'chemistry', 'physics', 'biology', 'geography', 'maths'}
{'chemistry', 'biology'}

In [ ]:
# the way to create empty sets tuples and lists

empty_set = {}        #only for the set criteria using the symbolizing bracket doisent work " {} "
empty_set = set()

empty_tuple = ()
empty_tuple = tuple()

empty_list = []
empty_list = list()

In [ ]:
#dictionary making

student = {"name" : "sakhya" , "dept" : "CSE" , "roll" : "39"}
print(student)
print(student['name'])
print(student.get("name"))
print(student.get("sankhya")) #shows dosent exist when its in the oppesite side

student["phone"] = "8910735871"
student["name"] = "jhilam"  #will update the name in the list
print(student)
print(student.get("phone"))

student.update({"name" : "samrat" , "dept" : "it"}) #this is a wholw another way to update a list
print(student)                                      #and has to be done in two diffderent lines or it will not work
del student["dept"]           #or u can use the pop variable to get the value that is popped of from the set
print(student)

print(student.keys())
print(student.values())
print(student.items())
print(len(student))                #toi get the amount of variaables in the set

#for looping or for diaplaying the values o fthe set in a list format
for keys in student:
  print(keys)
for values in student:
  print(values)
for keys, values in student.items():
  print(keys, values)
  print(values, keys)  #you can re write the formation of the output in here

{'name': 'sakhya', 'dept': 'CSE', 'roll': '39'}
sakhya
sakhya
None
{'name': 'jhilam', 'dept': 'CSE', 'roll': '39', 'phone': '8910735871'}
8910735871
{'name': 'samrat', 'dept': 'it', 'roll': '39', 'phone': '8910735871'}
{'name': 'samrat', 'roll': '39', 'phone': '8910735871'}
dict_keys(['name', 'roll', 'phone'])
dict_values(['samrat', '39', '8910735871'])
dict_items([('name', 'samrat'), ('roll', '39'), ('phone', '8910735871')])
3
name
roll
phone
name
roll
phone
name samrat
samrat name
roll 39
39 roll
phone 8910735871
8910735871 phone

In [ ]:
#coordination boolians in python or if else statement functions
#there are also 3 statements and,or,not

language = input("enter the language you want to write the code in : ")

if language == "python":
  print("the language you are typing the code in is python")
elif language == "java":
  print("the language you are typing the code in is java")
elif language == "javascript":
  print("the language you are typing the code in is javascript")
elif language == "c++":
  print("the language you are typing the code in is C++")
else:
  print("invalid programming language")

enter the language you want to write the code in : python
the language you are typing the code in is python

In [ ]:
user = "admin"
logged_in = True

if user == "admin" and logged_in:
  print("welcome !! admin ")
else :
  print("fuck of you bitch ass nigga !!")


user1 = "samrat"
loggedin = False

if user1 == "sankhya" or loggedin:
  print("welcome !! sankhya")
else:
  print("who the fuck are you !?")


user2 = "jhilaam"
loggedIN = True

if not loggedIN:
  print("who thw fuck are you !?")
else:
  print("welcome !! jhilam bhattyacharjee")


condition = None                              # we can also use None instead of the False boolian or u can use the empty set bumber 0 for false value and any other number than 0 for posative value ans also the lists touples annd other thing or any kind of empty thing to set the variablee factor of the coindition as "0"
if condition:                                  #means the condition is true
  print("the condition you wrote is true ")
else:
  print("The condition you wrote is false")

welcome !! admin
who the fuck are you !?
welcome !! jhilam bhattyacharjee
The condition you wrote is false

In [ ]:
#taking about the for loops and while loops
number = [1,2,3,4,5]

for num in number :          #is going to loop out the numbers in the list
  if num == 3:               #statement to run the programme folling in a certain position of the output
    print("found !!")        #printing the ststemet found !! instead the integer 3 and then start looping anagin or stop
    continue # break         #we can use both thee break and continue statement in this programme too make it run diffferently
  print(num)                 #prints thee list


for num in number :
  for letter in 'abc' :
    print(letter, num)       #prints out a number for each of the letters

1
2
found !!
4
5
a 1
b 1
c 1
a 2
b 2
c 2
a 3
b 3
c 3
a 4
b 4
c 4
a 5
b 5
c 5

In [ ]:
for i in range(1,11):
  #print(i+1)         #the value in the 1st place gets included but the last value in the vracket dosent , its runs upto the value
  print(i)

1
2
3
4
5
6
7
8
9
10

In [ ]:
x = 0

while x < 10:
  if x == 5 :
    print("found it !!")
    break
  print(x)
  x = x+1

0
1
2
3
4
found it !!

In [ ]:
#functions

def copy_right_text():   #we dont hate to rewrite the print statement everytime we can just do thee honors by typing the same printing value in one function
  print("(CR)")

copy_right_text()
copy_right_text()
copy_right_text()
copy_right_text()
copy_right_text()

def hello_world():
  return "hello world !!"

print(hello_world())
print(hello_world().upper())
print(hello_world().lower())


def programme(greeting, name = "user@007"):   #in the 2nd function the data can be gien in the fist bracket used in the function or in thee function value reader
  return "{} , {} !!".format(greeting, name)

print(programme("How's your day going" , name = "corey"))   #this function will get morte experties

(CR)
(CR)
(CR)
(CR)
(CR)
hello world !!
HELLO WORLD !!
hello world !!
How's your day going , corey !!

In [ ]:
calculator = input("enter the operator(+ , - , * , /) : ")

a = int(input("enter the 1st value : "))
b = int(input("enter the 2nd value : "))

if calculator == "+":
  def programme(a,b):
    print("\nthe addition of those numbers you written are : ")
    return "{} + {} = {}".format(a, b, a+b)

  print(programme(a,b))

elif calculator == "-":
  def programme(a,b):
    print("\nthe substraction of those numbers you written are : ")                   #python calculator
    return "{} - {} = {}".format(a, b, a-b)

  print(programme(a,b))

elif calculator == "*":
  def programme(a,b):
    print("\nthe multiplication of those numbers you written are : ")
    return "{} * {} = {}".format(a, b, a*b)

  print(programme(a,b))

elif calculator == "/":
  def programme(a,b):
    print("\nthe divition of those numbers you written are : ")
    return "{} / {} = {}".format(a, b, a/b)

  print(programme(a,b))

else:
  print("Invalid Input !!")

enter the operator(+ , - , * , /) : +
enter the 1st value : 20
enter the 2nd value : 20

1the addition of those numbers you written are :
20 + 20 = 40

In [ ]:
def info(*args,**kwargs):      #args = arguments , kwargs = key word arguments (agra contains any kind of arguments, and kwargs contains key words that makes a dictionary)
  print(args)
  print(kwargs)

print(info("hello", 12, age = 25, name = "sankhya"))

('hello', 12)
{'age': 25, 'name': 'sankhya'}
None

In [ ]:
def info(*args,**kwargs):
  print(args)
  print(kwargs)

courses = ['maths' , 'history']
about = {"name ": "sankhya" , "age" : 12}       #the kwargs will be empty because there is no dictionary in the print menu
#                                                          ^
#                                                          |
#print(info(courses,about))  ------------------------------
print(info(*courses,**about))
#* is the indication of the normal values
#and ** is the indication of the dictuinary values

('maths', 'history')
{'name ': 'sankhya', 'age': 12}
None

In [ ]:
month_days = [ 0,31,28,31,30,31,30,31,31,30,31,30,31]

year = int(input("write the year : "))
month = int(input("writhe the number of the month : "))

def leap_year(year):

  return year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)

def days_in_month(year,month):

  if not 1 <= month <= 12 :
    return "invalid input !!"

  if month == 2 and leap_year(year):
    return 29

  return month_days[month]

print(days_in_month(year,month))

write the year : 2022
writhe the number of the month : 6
30

libraries


what i got to know is there are a lot of libraries in built in the python programme and we can make our libraries from any kinf of files

we juast have to name them in a certain form and then import the file into anoother file saying that it is a library

like : import sankhya

and also there is a way we can find the list of inbuilt libraries in the pycharm folder or thee library section

and thee code to find the list of libraries in written below :

In [ ]:
import os
print(os.__file__)
print(dir(os)) #to get the attributes we can access from the module          #here the full form of dir is directory
#you havr to do it in your pycharm or the software you use to code to get the file locatrion of the libraries then paste it in the file manager and you get to read whats inside of it

In [ ]:
num = int(input("enter th enumber you want the multiplication table of : "))
print("here is the mulplication table of number {}".format(num))
for n in range(1,11):
  print("{} * {} = {}".format(num, n, num*n))

enter th enumber you want the multiplication table of : 11
here is the mulplication table of number 11
11 * 1 = 11
11 * 2 = 22
11 * 3 = 33
11 * 4 = 44
11 * 5 = 55
11 * 6 = 66
11 * 7 = 77
11 * 8 = 88
11 * 9 = 99
11 * 10 = 110

In [ ]:
import math
numbers = [ 1,2,3,4,5,6,7,8,9,10 ]

print(sum(numbers))

55

In [ ]:
total = 0

numbers = [1,2,3,4,5,6,7,8,9,10]

for num in range(0,len(numbers)+1):
  total = total + num

print(total)

55

In [ ]:
number = int(input("enter the number upto you want to get the even numbers : "))

for num in range(0,number+1):
  if (num % 2 == 0):
    print("{}".format(num))

enter the number upto you want to get the even numbers : 20
0
2
4
6
8
10
12
14
16
18
20

In [ ]:
item = int(input("enter the item you wanna find : "))
items = [1,2,3,4,5,6,7,8,9,10]

if item in items:
  print("item found !!")

else :
  print("item not found !!")

enter the item you wanna find : 11
item not found !!

In [ ]:
print("the list we have is. ")

for n in range(1,11):
  print(n)

print("\nafter removing the even numbers from the list we get ")

for num in range(1,11):
  if num % 2 != 0:
    print("{}".format(num))

the list we have is.
1
2
3
4
5
6
7
8
9
10

after removing the even numbers from the list we get
1
3
5
7
9

In [ ]:
num = int(input("enter the number : "))
i = 1
print("the multiplication table of the num {} is :".format(num))
while i <= 10:
  print("{} * {} = {}".format(num , i , num*i))
  i = i+1

enter the number : 11
the multiplication table of the num 11 is :
11 * 1 = 11
11 * 2 = 22
11 * 3 = 33
11 * 4 = 44
11 * 5 = 55
11 * 6 = 66
11 * 7 = 77
11 * 8 = 88
11 * 9 = 99
11 * 10 = 110

In [ ]:
num = int(input("enter the number : "))
i = 1
total = 0
while i <= num:
  total = total + i
  i = i + 1
print("the sum of the numbers is : {}".format(total))

enter the number : 12
the sum of the numbers is : 78

In [ ]:
sum = 0
count = 0

while count < 10:
    num = float(input("Enter a number: "))

    if num < 0:
        continue
        #break

    sum += num
    count += 1

print("Sum of the entered numbers:", sum)

Enter a number: 1
Enter a number: 1
Enter a number: 1
Enter a number: -2
Enter a number: 22
Enter a number: 12
Enter a number: 1
Enter a number: -34
Enter a number: 3
Enter a number: 44
Enter a number: -22
Enter a number: 1
Enter a number: 11
Sum of the entered numbers: 97.0

In [ ]:
first_list = ["abcd" , 147 , 2.43, "tom" , 74.8]
for words in first_list:
  print(words)
print(first_list)
print(first_list[0])
print(first_list[1:3])
print(first_list[:3])
print(len(first_list))

abcd
147
2.43
tom
74.8
['abcd', 147, 2.43, 'tom', 74.8]
abcd
[147, 2.43]
['abcd', 147, 2.43]
5

In [ ]:
first_list = ["abcd" , 147 , 2.43, "tom" , 74.8]
small_list = [222 , "tom"]

for x in first_list:
  if x in small_list:
    first_list.remove(x)
    #small_list.remove(x)
    print(first_list)
    print(small_list)

for elements in small_list:
  print(elements)

print(small_list * 2)

['abcd', 147, 2.43, 74.8]
[222, 'tom']
222
tom
[222, 'tom', 222, 'tom']

In [ ]:
first_list = {"abcd" , 147 , 2.43, "tom" , 74.8}
small_list = {222 , "tom"}

print(first_list.union(small_list))

{'abcd', 2.43, 147, 74.8, 222, 'tom'}

In [ ]:
first_list = ["abcd" , 147 , 2.43, "tom" , 74.8]
small_list = [222 , "tom"]

concentrated_list = first_list + small_list

print(concentrated_list)

['abcd', 147, 2.43, 'tom', 74.8, 222, 'tom']

In [ ]:
first_tuple = ("abcd" , 147 , 2.43, "Tom" , 74.8)
small_tuple = (222 , "Tom")

print(first_tuple)
#for element in first_tuple():        #impossible because the tuple elemet is not callable
  #print(element)

print(first_tuple[0])
print(first_tuple[1:3])
print(first_tuple[2:])
print(len(first_tuple))

complete_tuple = first_tuple + small_tuple    #dosent eleminate the same thing like the set function ,prints whatever is in the tuple
print(complete_tuple)                         #can also be called the concentrated tuple
print(small_tuple * 2)


"""dont know how to """

('abcd', 147, 2.43, 'Tom', 74.8)
abcd
(147, 2.43)
(2.43, 'Tom', 74.8)
5
('abcd', 147, 2.43, 'Tom', 74.8, 222, 'Tom')
(222, 'Tom', 222, 'Tom')

'dont know how to '

In [ ]:
#python recurtion

def factorial(x):
  if x == 1:
    return 1
  else:
    return (x * factorial(x-1))

num = int(input("enter th enumber you want to calculate the factorial of : "))
print(factorial(num))

enter th enumber you want to calculate the factorial of : 12
479001600

In [ ]:
greet = lambda  : print("hello world !!")

greet()

hello world !!

In [ ]:
#lambda functions are the single line functions which are defimned without any name
greet = lambda name : print("how's your day going !! ,",name)

greet("sankhya")

how's your day going !! , sankhya

In [ ]:
def double(x):
  return x * 2

double(2)

4

In [ ]:
double = lambda n : n * 2

double(3)

6

In [ ]:
dictionary_1 = {"name":"sankya" , "dept":"coms" , "roll":39 , "greetings":"hello"}
dictionary_2 = {"name":"tiyasa" , "dept":"it" , "roll":38}

#if there is something same in the dictionary with the same header element then the update function will change them in the new one

dictionary_1.update(dictionary_2)
print(dictionary_1)

{'name': 'tiyasa', 'dept': 'it', 'roll': 38, 'greetings': 'hello'}

In [ ]:
dictionary_1 = {"name":"sankhya" , "dept":"coms" , "roll":39 , "greetings":"hello"}

if "name" in dictionary_1:
  print("found name !!")

else:
  print("not in the dictionary !!")

name
found name !!

In [ ]:
calculator = input("enter an operator (+,-,*,/) : ")

num_1 = int(input("enter the 1st number : "))
num_2 = int(input("enter the 2nd number : "))

if calculator =="+":
  print("{} + {} = {}".format(num_1, num_2 ,num_1+num_2))
elif calculator =="-":
  print("{} - {} = {}".format(num_1, num_2 ,num_1-num_2))
elif calculator =="*":
  print("{} * {} = {}".format(num_1, num_2 ,num_1*num_2))
elif calculator =="/":
  print("{} / {} = {}".format(num_1, num_2 ,num_1/num_2))
else:
  print("invalid input !!")

enter an operator (+,-,*,/) : +
enter the 1st number : 12
enter the 2nd number : 23
12 + 23 = 35

In [ ]:
word = input("Enter a word: ")
num_times = int(input("Enter the number of times to repeat: "))

for _ in range(num_times):

    print(word)

Enter a word: suor er baccha college

In [6]:
a = int(input("Enter a number between (0...999) : "))

if a <= 9:
  print("the number you entered is a 1 digit number .")
elif a <= 99:
  print("the number you entered is a 2 dight number . ")
elif a <= 999:
  print("the number you entered is a 3 digit number .")
else:
  print("invalid entry !!")

Enter a number between (0...999) : 888
the number you entered is a 3 digit number .

In [10]:
num = int(input("enter a number between (0...999) : "))

if num < 0 or num > 999:
  print("invalid entry !!")
else:
  if num < 10:
    print("the number you entered is a single digit number.")
  else:
    if num < 100:
      print("the number you entered is a double digit number.")
    else:
      if num < 1000:
        print("the number you entered is a triple dight number.")

ennter a number between (0...999) : 333
the number you entered is a triple dight number.

range(9)

the output will print upto the written number


range(3,10)

the loop will start from the number written in the first bracket first , and ends before the number entered in the first bracket

range(3,20,2)

the loop will start from the number

the loop will continue upto the laast number

it will step 2 classes for the 2 in written in the range

like  the code underneath

In [18]:
for x in range(9):
  print(x)
print("____________________________")
for num in range(3,10):
  print(num)
print("____________________________")
for sankhya in range(3,20,2):
  print(sankhya)
print("____________________________")
for hi in range(10,3,-1):
  print(hi)

0
1
2
3
4
5
6
7
8
____________________________
3
4
5
6
7
8
9
____________________________
3
5
7
9
11
13
15
17
19
____________________________
10
9
8
7
6
5
4

In [20]:
for num in range(15,21):
  print("the number is {} ".format(num))
  print("the cube of the number is : {}".format(num * num * num))

the number is 15
the cube of the number is : 3375
the number is 16
the cube of the number is : 4096
the number is 17
the cube of the number is : 4913
the number is 18
the cube of the number is : 5832
the number is 19
the cube of the number is : 6859
the number is 20
the cube of the number is : 8000

In [25]:
for num in range(1,10,2):
  print("square root of", num , end = " ")
  print("is {} .".format(num**0.5))

  #we can use the end function to connect two print statements in a single line which could not be done with the format function.

square root of 1 is 1.0 .
square root of 3 is 1.7320508075688772 .
square root of 5 is 2.23606797749979 .
square root of 7 is 2.6457513110645907 .
square root of 9 is 3.0 .

In [4]:
print("---your poem here---")
name = "sankhyapriyo dey"
print("hello what's your name : {}".format(name))

---your poem here---
hello what's your name : sankhyapriyo dey

In [26]:
num_grades = int(input("enter the number of grades you have : "))
grades = []
bucket = 0
for i in range(0,num_grades,1):
    grade = float(input("enter the grade : "))
    grades.append(grade)
for i in range(0,num_grades,1):
    print(grades[i])                   #we have to add the [i] or the last number in the list will continue printing  
print("here are your grades buddy !!")    
for i in range(0,num_grades,1):
    bucket = bucket + grades[i]
average = bucket / num_grades 
print("")
print("and, here are the avg of your grades , {}".format(average))

12.0
34.0
23.0
here are your grades buddy !!

and, here are the avg of your grades , 23.0

In [20]:
numbers = int(input("enter how many numbers you have to calculate the average of : "))
num_tuple = []
addition = 0
for i in range(0,numbers,1):
    num = int(input("enter the numbers : "))
    num_tuple.append(num)
for total in num_tuple:
    addition = addition + total     
avg = addition / numbers 
print(avg)
print("here is the avg of the numbers you written !!")

19.0
here is the avg of the numbers you written !!

In [1]:
numbers = int(input("enter how many grades you have too input in the array : "))
numbers_list = []
high_grades = 0 
low_grades = 100
for i in range(0,numbers,1):
    num = int(input("enter a grade : "))
    numbers_list.append(num)
print("the array of grades you entered is : ",numbers_list)  
for i in range(0,numbers,1):
    if high_grades < numbers_list[i]:
        high_grades = numbers_list[i]
print("the highest number in the array you written is : ",high_grades)
for i in range(0,numbers,1):
    if low_grades > numbers_list[i]:
        low_grades = numbers_list[i]
print("the lowest number in the array you written is : ",low_grades)
for i in range(0,numbers-1,1):
    for i in range(0,numbers-1,1):
        if numbers_list[i] > numbers_list[i+1]:
            box_1 = numbers_list[i] 
            numbers_list[i] = numbers_list[i+1]
            numbers_list[i+1] = box_1
print("the numbers in the array you written in a lower to greater order : ")      
for i in range(0,numbers,1):
    print(numbers_list[i])
print("the array of grades you entered is : ",numbers_list)  
for i in range(0,numbers-1,1):
    for i in range(0,numbers-1,1):
        if numbers_list[i] < numbers_list[i+1]:
            box_1 = numbers_list[i] 
            numbers_list[i] = numbers_list[i+1]
            numbers_list[i+1] = box_1
print("the numbers in the array you written in a greater to lower order : ")      
for i in range(0,numbers,1):
    print(numbers_list[i])

the array of grades you entered is :  [12, 11, 13, 15, 23, 10, 19, 17, 22, 21, 23, 32]
the highest number in the array you written is :  32
the lowest number in the array you written is :  10
the numbers in the array you written in a lower to greater order :
10
11
12
13
15
17
19
21
22
23
23
32
the array of grades you entered is :  [10, 11, 12, 13, 15, 17, 19, 21, 22, 23, 23, 32]
the numbers in the array you written in a greater to lower order :
32
23
23
22
21
19
17
15
13
12
11
10

In [4]:
import pickle

name = ["sankhya","subhas","saswati","jhilam"]
grades = [100,99,98,97]
x = 103                                  #first we have to declare the values of the functions and then we have to dump those values in the pickle platform and then print values we have stored the pickle values in 
y = "sankhya1"
fruits = ["mango","lemon","hemlo","guys"]

with open("hello.pkl","wb") as f :        # wb means write binary 
    pickle.dump(name,f)
    pickle.dump(grades,f)
    pickle.dump(x,f)
    pickle.dump(y,f)
    pickle.dump(fruits,f)
    pickle.dump(3,f)
    pickle.dump("sankhya",f)

with open("hello.pkl","rb") as f2:         #rb means read binary 
    a = pickle.load(f2)
    b = pickle.load(f2)
    c = pickle.load(f2)
    d = pickle.load(f2)
    e = pickle.load(f2)
    f = pickle.load(f2)
    g = pickle.load(f2)
    
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

['sankhya', 'subhas', 'saswati', 'jhilam']
[100, 99, 98, 97]
103
sankhya1
['mango', 'lemon', 'hemlo', 'guys']
3
sankhya

In [6]:
import pickle

name = ["sankhya","subhas","saswati","jhilam"]
grades = [100,99,98,97]
x = 103
y = "sankhya1"
fruits = ["mango","lemon","hemlo","guys"]
data = [name,grades,x,y,fruits]                  #putting all of them values in one function and then looping it to print the values in one list 

with open("hello.pkl","wb") as f :        # wb means write binary 
    pickle.dump(data,f)

with open("hello.pkl","rb") as f2:         #rb means read binary 
    data_prt = pickle.load(f2)

print(data_prt)
print("")
for list in data_prt:
    print(list)

[['sankhya', 'subhas', 'saswati', 'jhilam'], [100, 99, 98, 97], 103, 'sankhya1', ['mango', 'lemon', 'hemlo', 'guys']]

['sankhya', 'subhas', 'saswati', 'jhilam']
[100, 99, 98, 97]
103
sankhya1
['mango', 'lemon', 'hemlo', 'guys']

In [4]:
print("here we are going to input some numbers and get the output of them :")
num = int(input("enter how many numbers you want to enter : "))
j = 0 
grades = []
while (j < num):
    numbers = int(input("enter a number : "))
    grades.append(numbers)
    j = j + 1 
j = 0    
while (j < num):
    print("the values you entered are : ",grades[j])
    j = j + 1

here we are going to input some numbers and get the output of them :
the values you entered are :  12
the values you entered are :  24
the values you entered are :  34

In [6]:
import pickle

no_students = int(input("enter the number of students : "))
grades = []
names = []

for i in range(0,no_students,1):
    name = input("enter the name of the student : ")
    names.append(name)
    form = "enter " + name + "'s grade :"
    number = float(input(form))
    grades.append(number)
    
with open("name_grade.pkl","wb") as data_write:    
    pickle.dump(no_students,data_write)
    pickle.dump(grades,data_write)
    pickle.dump(names,data_write)

with open("name_grade.pkl","rb") as data_read:    
    a = pickle.load(data_read)
    b = pickle.load(data_read)
    c = pickle.load(data_read)
    
print("the number of students you have is : ",a)
print("here are the grades : ",b)
print("names : ",c)

the number of students you have is :  4
here are the grades :  [90.0, 89.0, 85.0, 95.0]
names :  ['sankhya', 'aniket', 'tiyasa', 'sahil ']

In [1]:
import pickle

with open("name_grade.pkl","rb") as data_read:    
    num_students = pickle.load(data_read)
    grades = pickle.load(data_read)
    names = pickle.load(data_read)
    
print(num_students)
print(grades)
print(names)

while (1 == 1):
    name = input("enter the name of the student you want to check the grades of : ")
    for i in range(0,num_students,1):
        if names[i] == name:
            print(name , "'s grades are : ", grades[i])

5
[99.0, 97.0, 95.0, 93.0, 94.0]
['sankhya', 'sahil', 'aniket', 'tiyasa ', 'sauradipto ']
sankhya 's grades are :  99.0
sahil 's grades are :  97.0
aniket 's grades are :  95.0
tiyasa  's grades are :  93.0
sauradipto  's grades are :  94.0

In [11]:
#we have to input the numbers , output them get the avg , get the high and the lowest number 

def input_num(nums):
    grades = []
    for i in range(0,nums,1):
        grade = float(input("enter the grade : "))
        grades.append(grade)
    return grades

def printGrades(nums,x):
    for i in range(0,nums,1):
        print(x[i])

def avgGrades(nums,x):
    total = 0 
    for i in range(0,nums,1):
        total = total + x[i]
    average = total/nums     
    return average
    
def topBottom(nums,x):
    topG = 0
    bottomG = 100
    for i in range(0,nums,1):
        if(x[i] < bottomG):
            bottomG = x[i]
        if(x[i] >  topG):
            topG = x[i]
    return topG,bottomG

input_grades = int(input("enter the number of grades you have : "))
myGrades = input_num(input_grades)
printGrades(input_grades,myGrades)
avg = avgGrades(input_grades,myGrades)
print("the avg of the entered functions are : ",round(avg,1))
topG,bottomG = topBottom(input_grades,myGrades)
print("your high grades is : ",topG)
print("you low grades is : ",bottomG)

12.0
23.0
34.0
the avg of the entered functions are :  23.0
your high grades is :  34.0
you low grades is :  12.0